### ISSUE TITLE
Tuning data distribution

### ISSUE THREAD

**Issue by naikshubham** [vsatyakumar/automatic-local-outlier-factor-tuning#1]
Hi team,

The tuning should be done only on normal data or data with anomalies in it?

**Comment by vsatyakumar** [comment]
Hey Shubham, apologies for the delayed response. The authors of this publication (not me) have assumed that both inliers and outliers have gaussian distributions. The tuning should be performed on your data with anomalies. You can then use the tuned hyperparameters to fit a LOF model on the same data and optimally detect outliers.
